#!/bin/bash
#
# starts tmux sessions for each valid torrent in LINBODIR
# thomas@linuxmuster.net
# 20250520
#

# read environment
. /usr/share/linuxmuster/helperfunctions.sh || exit 1
THELPER=$LINBOSHAREDIR/linbo-torrenthelper.sh
LINBOIMGEXT="qcow2 qdiff iso"

# get ctorrent options from file
[ -e /etc/default/linbo-torrent ] && source /etc/default/linbo-torrent
isinteger "$PIECELEN" && plopt="-l $PIECELEN"

# start of functions

# help message
usage(){
  echo
  echo "Info: linbo-torrent manages the torrent tmux sessions of linbo images."
  echo
  echo "Usage:"
  echo " linbo-torrent <start|stop|restart|reload|status|create|check> [image_name]"
  echo " linbo-torrent attach <image_name|session_name>"
  echo " linbo-torrent update-otr"
  echo
  echo "Note:"
  echo " * Only qcow2 & qdiff image files located below $LINBOIMGDIR are processed."
  echo " * The commands \"start\", \"stop\" and \"restart\" may have optionally an image"
  echo "   filename as parameter. In this case the commands are only applied to the tmux"
  echo "   session of the certain file. Without an explicit image filename the commands"
  echo "   were applied to all image file sessions currently running."
  echo " * An image filename parameter is mandatory with the commands \"check\", \"create\""
  echo "   and \"attach\"."
  echo " * \"check\" checks if the image file matches to the correspondig torrent."
  echo " * \"create\" creates/recreates the torrent of a certain image file."
  echo " * \"status\" shows a list of currently running torrent tmux sessions."
  echo " * \"attach\" attaches a torrent tmux session of a certain image. An image or"
  echo "   session name must be given as parameter."
  echo "   Press [CTRL+B]+[D] to detach the session again."
  echo " * \"reload\" is the identical to \"restart\" and is there for backwards compatibility."
  echo " * \"update-otr\" updates the opentracker whitelist $OTRWLIST."
  echo
  exit 1
}

# save torrent hash
save_hash(){
  local torrent="$1"
  local hash="${torrent%.torrent}.hash"
  echo "Saving hash of $(basename "$torrent") ..."
  LANG=C btcheck -ni "$torrent" | grep ^'Torrent Hash' | awk '{print $4}' > "$hash" || echo "Failed to save torrent hash!"
}

# updates the opentracker whitelist
update_otr(){
  local torrent
  local hash
  # save missing torrent hashes
  find "$LINBOIMGDIR" -maxdepth 2 -name "*.torrent" | while read -r torrent; do
    [ -s "${torrent%.torrent}.hash" ] || save_hash "$torrent"
  done
  echo "Updating opentracker torrent whitelist ..."
  cat "$LINBOIMGDIR"/*/*.hash 2> /dev/null | sort -u > "$OTRWLIST"
  chown "$OTRUSER":"$OTRUSER" "$OTRWLIST"
  chmod 640 "$OTRWLIST"
  systemctl reload opentracker.service
}

# check torrent
check(){
  local image="$(basename "$IMGLIST")"
  local torrent="$image.torrent"
  local tdir="$(dirname "$IMGLIST")"
  cd "$tdir"
  echo "Checking $torrent ..."
  btcheck -v "$torrent" || exit 1
}

# creates torrent files
create(){
  local image="$(basename "$IMGLIST")"
  local tdir="$(dirname "$IMGLIST")"
  local torrent="${image}.torrent"
  local session="${torrent//./_}"
  # stop torrent service
  linbo-torrent status | grep -q ^"$session" && linbo-torrent stop "$IMGLIST"
  # skip already running torrents
  echo "Creating $torrent ..."
  cd "$tdir"
  rm -f "$torrent"
  if buildtorrent --announce http://$serverip:6969/announce "$image" "$torrent" ; then
    # save torrent hash
    save_hash "$torrent"
    [ "$START" = "no" ] || linbo-torrent start "$IMGLIST"
  else
    echo "Failed!"
    exit 1
  fi
  # create infofile for isoimages
  local ext="$(echo ${image##*.} | tr A-Z a-z)"
  [ "$ext" = "iso" ] && "$LINBOSHAREDIR/linbo-mkinfo.sh" "$image"
}

# starts torrent tmux sessions
start(){
  local item
  local torrent
  local image
  local tdir
  local session
  for item in $IMGLIST; do
    image="$(basename "$item")"
    torrent="${image}.torrent"
    tdir="$(dirname "$item")"
    session="${torrent//./_}"
    cd "$tdir"
    if [ ! -s "$image" ]; then
      echo "Image $image does not exist! Skipping this torrent."
      continue
    fi
    # skip already running torrents
    if linbo-torrent status | grep -qw ^"$session"; then
      echo "tmux session $session is already running."
      continue
    fi
    # create torrent file if there is none
    if [ ! -e "$torrent" ]; then
      START="no" linbo-torrent create "$item" || continue
    fi
    echo -n "Starting tmux session $session ... "
    tmux new -ds "$session" "$THELPER $torrent ; exec $SHELL"
    sleep 1
    if linbo-torrent status | grep -qw ^"$session"; then
      echo "Ok!"
    else
      echo "Failed!"
    fi
  done
}

stop(){
  if [ -n "$SESSION" ]; then
    linbo-torrent status | grep -qw ^"$SESSION" || return
    tmux kill-session -t "$SESSION"
  else
    local item
    linbo-torrent status | awk -F\: '{print $1}' | while read item; do
      tmux kill-session -t "$item"
    done
  fi
}

attach(){
  if ! tmux list-sessions | grep -qw "$SESSION"; then
    echo "There is no session $SESSION."
    exit 1
  fi
  echo "Hint: Detach tmux session with [CTRL+B]+[D]."
  sleep 3
  tmux attach -t "$SESSION"
}

status(){
  tmux list-sessions | grep _torrent
}

find_images(){
  local search="$(basename "$1")"
  if [ -n "$search" ]; then
    find "$LINBOIMGDIR" -maxdepth 2 -name "$search"
    return
  fi
  local IMGLIST
  for search in $LINBOIMGEXT; do
    IMGLIST="$IMGLIST $(find "$LINBOIMGDIR" -maxdepth 2 -name \*.$search)"
  done
  # trim leading and trailing spaces
  echo $IMGLIST | awk '{$1=$1};1'
}

# end of functions

# check parameters
if [ -n "$2" ] ; then
  # trap torrent parameter
  image="${2/.torrent/}"
  case "$image" in
    *.qcow2|*.qdiff|*.iso)
      if [ -e "$image" ]; then
        IMGLIST="$image"
      else
        IMGLIST="$(find_images "$image")"
      fi
      if [ ! -e "$IMGLIST" ]; then
        echo "Image file $(basename $image) not found."
        usage
      fi
      filename="$(basename "$IMGLIST")"
      SESSION="${filename//./_}_torrent"
      ;;
    *_torrent)
      if [ "$1" = "attach" ]; then
        SESSION="$image"
      else
        usage
      fi
      ;;
    *) usage ;;
  esac
else
  case "$1" in
    stop|status|update-otr) ;;
    attach|check|create) usage ;;
    *)
      IMGLIST="$(find_images)"
      if [ -z "$IMGLIST" ]; then
        echo "No linbo images found."
        exit 0
      fi
      ;;
  esac
fi

case "$1" in
  start) start ; UPDATE_OTR="yes" ;;
  stop) stop ;;
  restart|reload) stop ; start ; UPDATE_OTR="yes" ;;
  status) status ;;
  create) create ; UPDATE_OTR="yes" ;;
  check) check ;;
  attach) attach ;;
  update-otr) UPDATE_OTR="yes" ;;
  *) usage ;;
esac

# opentracker whitelist update
[ -n "$UPDATE_OTR" ] && update_otr

exit 0
