#!/usr/bin/python3
#
# Filename     : linbo-remote
# Description  : Execute linbo commands on clients remotely per ssh, or
#                schedule them for the client's next boot. Thin launcher -
#                all logic lives in linbo_remote_cli.py (importable/testable),
#                see /usr/share/linuxmuster/linbo/.
# Signed-off by: thomas@linuxmuster.net
# Assisted by  : Claude
# Date         : 20260902
# GPL v3
#

import sys

sys.path.insert(0, '/usr/share/linuxmuster/linbo')
from linbo_remote_cli import main  # noqa: E402

if __name__ == '__main__':
    sys.exit(main())
