#!/bin/bash
#
# update-linbofs pre hook example
# thomas@linuxmuster.net
# 20231105
#

echo "### pre hook example ###"

# read linuxmuster environment
source /usr/share/linuxmuster/linbo/helperfunctions.sh || exit 1

# copies my script to linbofs
myscript="/root/linbofs/myscript.sh"
cp "$myscript" "$LINBOCACHEDIR/linbofs64/usr/bin"
